# F5TTS_v1_Base | E2TTS_Base
model = "PEFT-TTS_base"
ref_audio = "infer/examples/single/single_ref_kr.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "부모가 저지르는 큰 실수중 하나는, 자기 아이를 다른 집 아이와 비교하는 것이다."
gen_text = "사람은 겉과 속이 달라서는 안된다."
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"
output_file = "infer_cli_single.wav"